# Generated by Django 5.0.4 on 2024-04-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_livraria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.TextField(max_length=255),
        ),
    ]
