# Generated by Django 5.0.4 on 2024-04-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_livraria', '0002_alter_usuarios_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(max_length=255)),
                ('nome', models.TextField(max_length=255)),
                ('senha', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
