# Generated by Django 5.0.4 on 2024-04-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_livraria', '0004_alter_usuario_email_alter_usuario_senha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
