# Generated by Django 5.0.4 on 2024-04-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_livraria', '0005_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=30)),
                ('data_cadastro', models.DateField()),
                ('emprestado', models.BooleanField(default=False)),
                ('nome_emprestado', models.CharField(max_length=30)),
                ('data_devolucao', models.DateTimeField()),
                ('data_emprestimo', models.DateTimeField()),
                ('tempo_duracao', models.DateField()),
            ],
        ),
    ]
